# Generated by Django 4.2.6 on 2023-11-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_platform",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
