# Generated by Django 4.2.6 on 2023-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_rename_created_watchlist_created_at_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamplatform",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="streamplatform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
