# Generated by Django 4.2.6 on 2023-11-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "watchlist_app",
            "0005_streamplatform_created_at_streamplatform_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
